### PR TITLE
WIP readme explanation of env vars

### PR DESCRIPTION
**Pull request by davidv171**
#43 . I'm actually not sure myself what the last 2 env vars are, but I think this is a good starting point. I tried to be as brief, while still providing some info, based on what I was confused about personally when trying to set up a dev environment. Feedback is much appreciated

### CODE REVIEW

**Comment by legendofmiracles** [comment]
If this PR already touches the README, maybe also fix that it's supposed to be `env $(cat .env)` instead of only `env $(.env)`.

**Comment by davidv171** [comment]
> If this PR already touches the README, maybe also fix that it's supposed to be `env $(cat .env)` instead of only `env $(.env)`.

Added

**Comment by elkowar** [comment]
RE attachment cache stuff:
To log message attachments (images, etc) we have to locally cache them, as discord doesn't let us download them after a message has been deleted. thus, there is a cache directory and max-size for that. if the max-size is exceeded, it'll start deleting old attachments

**Comment by elkowar** [comment]
Thanks!

**Pull request merged**
