### PR TITLE
Show version on restart and add version command

### PR DESCRIPTION
**Pull request by elkowar**
This PR adds a !version command that shows the bot version, formatted as `<rev-number>.<short-commit-hash>`.
Additionally, it makes the bot send a message to #bot-stuff when it started, also showing the current version.

### CODE REVIEW

**Comment by mlvzk** [comment]
Dockerfile also needs to be changed, because it doesn't include .git or the git binary.

What if instead we did `option_env!("VERSION")` and built the docker image with `docker build . -t mlvzk/upbot --build-arg VERSION="$(git rev-parse --short HEAD)"`?

**Comment by elkowar** [comment]
Will building the dockerfile be automatic, or is that sth that we'll have to do manually? Should we then keep it in the build-script optionally, or just completely remove it there and just have <no rev>.<no hash> during development?

**Comment by mlvzk** [comment]
no build.rs, option_env evaluates at build time so you can put it right in the version command function. If you mean if we should fallback to `git` then there's no need, it's not useful in development anyway.

**Comment by elkowar** [comment]
so do i then use:
`docker build . -t mlvzk/upbot --build-arg VERSION="$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"`
in the Dockerfile and we're gucci?

**Comment by mlvzk** [comment]
yes

**Comment by elkowar** [comment]
Updated!

**Review by mlvzk — APPROVED** [review]

**Pull request merged**
